# -*- coding: utf-8 -*-
"""Project4 Student gradebook app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q3Whr279ZhaC0sU76KGnrCNBQcbDbosH
"""

# Week 6: Student Gradebook App
## project stores student marks and grades in a CSV file.

import csv

file_name = "student_grades.csv"

try:
    with open(file_name, "r", newline="") as file:
        pass

except FileNotFoundError:
    with open(file_name, "w", newline="") as file:
        writer = csv.writer(file)
        writer.writerow(["Name", "Subject", "Marks", "Grade"])

    print("Gradebook file created successfully.")

def calculate_grade(marks):
    if marks >= 80:
        return "A"
    elif marks >= 70:
        return "B"
    elif marks >= 60:
        return "C"
    elif marks >= 50:
        return "D"
    else:
        return "F"

def add_student():
    try:
        name = input("Enter student name: ").strip()
        subject = input("Enter subject name: ").strip()

        if name == "" or subject == "":
            raise ValueError("Name and subject cannot be empty.")

        marks = int(input("Enter marks from 0 to 100: "))

        if marks < 0 or marks > 100:
            raise ValueError("Marks must be between 0 and 100.")

        grade = calculate_grade(marks)

        with open(file_name, "a", newline="") as file:
            writer = csv.writer(file)
            writer.writerow([name.title(), subject.title(), marks, grade])

        print("Student record saved successfully.")
        print("Grade:", grade)

    except ValueError as error:
        print("Error:", error)

def view_students():
    try:
        with open(file_name, "r", newline="") as file:
            reader = csv.reader(file)
            next(reader)

            records_found = False

            print("\n===== ALL STUDENT RECORDS =====")

            for row in reader:
                records_found = True

                print("Name:", row[0])
                print("Subject:", row[1])
                print("Marks:", row[2])
                print("Grade:", row[3])
                print("--------------------")

            if records_found == False:
                print("No student records are available.")

    except FileNotFoundError:
        print("Gradebook file was not found.")
        print("Please run the setup cell first.")

while True:
    print("\n===== STUDENT GRADEBOOK =====")
    print("1. Add Student Record")
    print("2. View All Records")
    print("3. Exit")

    choice = input("Enter your choice: ").strip()

    if choice == "1":
        add_student()

    elif choice == "2":
        view_students()

    elif choice == "3":
        print("Gradebook closed.")
        break

    else:
        print("Invalid choice. Please enter 1, 2, or 3.")